### PR TITLE
[ROS-O] various cleanup

### PR DESCRIPTION
**Pull request by v4hn**
all but the last patch are required to compile with a current debian environment and are backward compatible.
I threw in the last one to avoid a serious looking warning by clang that actually has no effect here.

### CODE REVIEW

**Comment by jonbinney** [comment]
@v4hn what are the target linux distros and compiler versions for ROS-O? I don't see it in the target platforms REP

**Comment by v4hn** [comment]
Sorry for the late reply. Please see https://github.com/ros-o/ros-o (and my linked talk if you didn't watch it) for what ROS-O is and isn't. It's no "regular ROS distribution".

There is currently no limit on more current supported targets. Everything that remains compatible with Ubuntu 20.04 / the noetic REP entry should be contributed back.

**Comment by jonbinney** [comment]
@v4hn ah, that makes sense. Thank you for the work you're doing!

**Review by jonbinney — APPROVED** [review]
Doesn't look like it will break anything for noetic, so should be good.

**Pull request merged**
