### PR TITLE
LaserScanAngularRemovalFilter

### PR DESCRIPTION
**Pull request by kmhallen**
LaserScanAngularRemovalFilter allows the removal of sections of a LaserScan. I use it to remove pillars on my robot that are visible in the scan, but never move.

### CODE REVIEW

**Comment by vrabaud** [comment]
It seems to be the same as https://github.com/ros-perception/laser_filters/blob/indigo-devel/include/laser_filters/angular_bounds_filter.h except you modify the laser in place right ?

**Comment by kmhallen** [comment]
I am not sure what you mean by 'modify the laser in place'. That header file is where I started. angular_bounds_filter keeps the points inside and produces a smaller scan. angular_removal_filter keeps the points outside and replaces the removed points with range_max + 1.0.

**Comment by vrabaud** [comment]
I am not crazy about the name LaserScanAngularRemovalFilter : it is confusing as it is not removing anything. How about LaserScanAngularBoundsFilterInPlace ? http://en.wikipedia.org/wiki/In-place_algorithm

**Comment by kmhallen** [comment]
LaserScanAngularBoundsFilterInPlace is fine.

**Comment by vrabaud** [comment]
cool, please update your PR with the new naming. Thx

**Comment by kmhallen** [comment]
PR has been updated with new naming in 04f0925

**Pull request merged**
