### PR TITLE
Make laser_filters build for ros2 (on windows 10)

### PR DESCRIPTION
**Pull request by bfjelds**
Should go to a ROS2 branch, but I'm not sure how to create a PR for that :)

Working towards enabling laser_filters in ROS2. This provides ability to build and updates for ROS2 constructs (like Node vs NodeHandle, LaserScan's new namespace).

There are some gaps (TransformListener's waitForTransform, time handling, test code, parameter handling, timers), but it builds and runs.

### CODE REVIEW

**Comment by jonbinney** [comment]
@bfjelds great work, thanks for doing this!

I can create a branch for this. @wjwwood is there a best practice for naming of ROS2 branches in ROS1 repositories?

**Comment by wjwwood** [comment]
@jonbinney so far we've been just using the branch `ros2` for the equivalent of "master" for ros 2 support. Though we also have an `ardent` branch on our repositories from which we could do patch releases for the first official release. You could also use `ardent-devel` if that suited you.

My recommendation is just to use `ros2` for now, since this isn't released into ardent yet. Also the recommendation might evolve as we improve the migration guide and tools to help the ROS 1/2 stuff coexist.

**Comment by jonbinney** [comment]
Thanks @wjwwood . @bfjelds I've created a ros2 branch; can you open a new PR that targets it?

**Comment by wjwwood** [comment]
You can change the pr's target branch now, so no need to remake it 😉.

**Comment by jonbinney** [comment]
Whoooo crazy. Do that @bfjelds  :-)

**Comment by bfjelds** [comment]
Awesome!  Here's the new PR: https://github.com/ros-perception/laser_filters/pull/60.

**Comment by wjwwood** [comment]
Well, it was already done 😛, but #60 is fine too.
  
screen shot 2018-01-09 at 10 57 35 am

**Pull request closed without merging**
