### PR TITLE
Reduce computation cost of ScanShadowsFilter

### PR DESCRIPTION
**Pull request by nikolaseu**
Include #62 into ROS2 branch

### CODE REVIEW

**Comment by jonbinney** [comment]
Looks like CI failed for galactic because rosdep doesn't fetch dependency info for EOL distros by default anymore. I need to do two things:
- tell rosdep to fetch eol distros on CI (i'd like to check compatibility with galactic for now; no sense in breaking stuff unless needed)
- add H-turtle to CI

**Comment by jonbinney** [comment]
Fixing CI here: https://github.com/ros-perception/laser_filters/pull/174

**Comment by jonbinney** [comment]
@nikolaseu I've fixed some things in the CI configuration; could you rebase this PR on the ros2 branch?

**Comment by nikolaseu** [comment]
Done. Thanks Jonathan

**Comment by jonbinney** [comment]
Looks good, thanks @nikolaseu !

**Pull request merged**
