### PR TITLE
Update package.xml

### PR DESCRIPTION
**Pull request by asimay**
remove eigen dependency and tidy up cmake list reduncy

### CODE REVIEW

**Comment by asimay** [comment]
remove eigen dependency and tidy up cmake list reduncy

**Comment by jonbinney** [comment]
Thanks @asimay ! Can you revert the change to the maintainer email address in the `package.xml`?

**Comment by jonbinney** [comment]
Merged. Thanks @asimay!

**Comment by 130s** [comment]
Actually build error was captured on Travis. See [this line](https://travis-ci.org/ros-perception/laser_filters/jobs/112550481#L2444) for example.

**Comment by asimay** [comment]
ok. this is one by one comit action. i already put all commit in whole on yesterday. and delete one by one commit request.

**Pull request merged**
