### PR TITLE
feat: PolygonFilter

### PR DESCRIPTION
**Pull request by reinzor**
Filters LaserScan points inside or outside a specified polygon. This
filter also exposes a dynamic reconfigure server for reconfiguration.

### CODE REVIEW

**Comment by jonbinney** [comment]
This sounds very useful. I'll try to review the code this weekend.

**Comment by reinzor** [comment]
hi @jonbinney , did you have time to look into this?

**Comment by jonbinney** [comment]
@reinzor thanks for the reminder - let me look at it today.

**Comment by jonbinney** [comment]
@reinzor could you retarget this PR to the kinetic-devel branch? I'm now releasing kinetic and melodic from the kinetic-devel branch, and only indigo from the indigo-devel branch.

That will also make it OK to use C++11, since starting in kinetic that is supported: https://www.ros.org/reps/rep-0003.html#kinetic-kame-may-2016-may-2021

**Comment by reinzor** [comment]
sure

**Pull request closed without merging**
