### PR TITLE
add cmake_modules run dependency

### PR DESCRIPTION
**Pull request by jonbinney**
so that it compiles

### CODE REVIEW

**Comment by dirk-thomas** [comment]
This needs a new release into indigo in order to fix the Debian package: http://jenkins.ros.org/view/IbinT64/job/ros-indigo-laser-filters_binarydeb_trusty_amd64/

**Comment by jonbinney** [comment]
I did a release but forgot to bump the version number first. Will do another release.

**Comment by jonbinney** [comment]
Ok this should_ do it: https://github.com/ros/rosdistro/pull/3453

**Comment by tfoote** [comment]
this should be 1.7.0 in indigo as these changes are not compatible with the 1.6.x hydro release series.

**Comment by jonbinney** [comment]
Ooops... ok i've released 1.7.0: https://github.com/ros/rosdistro/pull/3457

**Pull request merged**
