### PR TITLE
Porting speckle filter to ROS2

### PR DESCRIPTION
**Pull request by Patrick-Lascombe**
Porting speckle filter to ROS2 which was missing for now

### CODE REVIEW

**Comment by jonbinney** [comment]
Looks like the CI is only failing because it tries to test the code with ROS1. I should update the CI jobs at some point....

@Patrick-Lascombe it looks like you copied the files over without preserving the commits. Could you instead cherry-pick the commits over so that we can tell where this came from in the future?

**Comment by Patrick-Lascombe** [comment]
Yes I copied the file from the ROS1 branch and "translated" it into ROS2, I don't know if there is a way to cherry pick the ROS 1 speckle filter file to make it appear in the commits ?

**Comment by Patrick-Lascombe** [comment]
Sorry I left this on the side for a while now, here is the [permalink](https://github.com/ros-perception/laser_filters/blob/2490b8aff7ac9be93e1ab68581146ca0c65eaa5a/src/speckle_filter.cpp) of the file I copied and translated to ROS2. 
I hope it is enough for the tracking of the speckle filter origin.

**Comment by jonbinney** [comment]
@Patrick-Lascombe yes you can copy over the original commit(s).  Please use the `git cherry-pick` command to copy over the original speckle filter commit(s), then reapply your change commits.

**Comment by pmusau17** [comment]
@Patrick-Lascombe wondering if you're around to do the cherry pick? I tried to do it on my end but think that I might be missing the final port of this [file](https://github.com/ros-perception/laser_filters/blob/2490b8aff7ac9be93e1ab68581146ca0c65eaa5a/src/speckle_filter.cpp)

**Comment by Patrick-Lascombe** [comment]
Sorry, I've had a lot of work lately and I couldn't take the time. I think that this file is from where I began the porting.
If it is not too urgent I'll try to cherry-pick and port again to ROS2 by the end of next week

**Comment by jonbinney** [comment]
I went ahead and made a new PR that cherry-picks the original speckle filter commits and the update commits from this PR: https://github.com/ros-perception/laser_filters/pull/122

I'll do some testing tomorrow before I merge it.

**Pull request closed without merging**
